apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
spec:
  capacity:
    storage: 1Gi  # Size of the storage
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/mysql-data  # Local path on your host machine
