apiVersion: v1
kind: Service
metadata:
  name: wordpress-sftp
spec:
  selector:
    app: wordpress
  ports:
  - protocol: TCP
    port: 22
    targetPort: 22
    nodePort: 30454 # Static NodePort value
  type: NodePort
