apiVersion: v1
kind: Secret
metadata:
  name: wordpress-db-secret
type: Opaque
data:
  WORDPRESS_DB_HOST: MTkyLjE2OC40OS4yOjMxMDYw  # base64 encoded value of '192.168.49.2:31060'
  WORDPRESS_DB_USER: cm9vdA==                  # base64 encoded value of 'root'
  WORDPRESS_DB_PASSWORD: cGFzc3dvcmQ=          # base64 encoded value of 'password'
  WORDPRESS_DB_NAME: d29yZHByZXNz              # base64 encoded value of 'wordpress'
